/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InscrevaSeRouteImport } from './routes/inscreva-se'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTramitesRouteImport } from './routes/app.tramites'
import { Route as AppSorteioRouteImport } from './routes/app.sorteio'
import { Route as AppSituacoesRouteImport } from './routes/app.situacoes'
import { Route as AppFuncoesRouteImport } from './routes/app.funcoes'
import { Route as AppEntrevistasRouteImport } from './routes/app.entrevistas'
import { Route as AppEditaisRouteImport } from './routes/app.editais'
import { Route as AppCredenciadosRouteImport } from './routes/app.credenciados'
import { Route as AppConvocacoesRouteImport } from './routes/app.convocacoes'
import { Route as AppContratosRouteImport } from './routes/app.contratos'
import { Route as AppCadastroRouteImport } from './routes/app.cadastro'
import { Route as AppEntrevistasAgendarRouteImport } from './routes/app.entrevistas.agendar'
import { Route as AppCredenciadosCadastrarRouteImport } from './routes/app.credenciados.cadastrar'
import { Route as AppContratosGerarRouteImport } from './routes/app.contratos.gerar'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InscrevaSeRoute = InscrevaSeRouteImport.update({
  id: '/inscreva-se',
  path: '/inscreva-se',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTramitesRoute = AppTramitesRouteImport.update({
  id: '/tramites',
  path: '/tramites',
  getParentRoute: () => AppRoute,
} as any)
const AppSorteioRoute = AppSorteioRouteImport.update({
  id: '/sorteio',
  path: '/sorteio',
  getParentRoute: () => AppRoute,
} as any)
const AppSituacoesRoute = AppSituacoesRouteImport.update({
  id: '/situacoes',
  path: '/situacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppFuncoesRoute = AppFuncoesRouteImport.update({
  id: '/funcoes',
  path: '/funcoes',
  getParentRoute: () => AppRoute,
} as any)
const AppEntrevistasRoute = AppEntrevistasRouteImport.update({
  id: '/entrevistas',
  path: '/entrevistas',
  getParentRoute: () => AppRoute,
} as any)
const AppEditaisRoute = AppEditaisRouteImport.update({
  id: '/editais',
  path: '/editais',
  getParentRoute: () => AppRoute,
} as any)
const AppCredenciadosRoute = AppCredenciadosRouteImport.update({
  id: '/credenciados',
  path: '/credenciados',
  getParentRoute: () => AppRoute,
} as any)
const AppConvocacoesRoute = AppConvocacoesRouteImport.update({
  id: '/convocacoes',
  path: '/convocacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppContratosRoute = AppContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AppRoute,
} as any)
const AppCadastroRoute = AppCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => AppRoute,
} as any)
const AppEntrevistasAgendarRoute = AppEntrevistasAgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => AppEntrevistasRoute,
} as any)
const AppCredenciadosCadastrarRoute =
  AppCredenciadosCadastrarRouteImport.update({
    id: '/cadastrar',
    path: '/cadastrar',
    getParentRoute: () => AppCredenciadosRoute,
  } as any)
const AppContratosGerarRoute = AppContratosGerarRouteImport.update({
  id: '/gerar',
  path: '/gerar',
  getParentRoute: () => AppContratosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/inscreva-se': typeof InscrevaSeRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/cadastro': typeof AppCadastroRoute
  '/app/contratos': typeof AppContratosRouteWithChildren
  '/app/convocacoes': typeof AppConvocacoesRoute
  '/app/credenciados': typeof AppCredenciadosRouteWithChildren
  '/app/editais': typeof AppEditaisRoute
  '/app/entrevistas': typeof AppEntrevistasRouteWithChildren
  '/app/funcoes': typeof AppFuncoesRoute
  '/app/situacoes': typeof AppSituacoesRoute
  '/app/sorteio': typeof AppSorteioRoute
  '/app/tramites': typeof AppTramitesRoute
  '/app/': typeof AppIndexRoute
  '/app/contratos/gerar': typeof AppContratosGerarRoute
  '/app/credenciados/cadastrar': typeof AppCredenciadosCadastrarRoute
  '/app/entrevistas/agendar': typeof AppEntrevistasAgendarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inscreva-se': typeof InscrevaSeRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/cadastro': typeof AppCadastroRoute
  '/app/contratos': typeof AppContratosRouteWithChildren
  '/app/convocacoes': typeof AppConvocacoesRoute
  '/app/credenciados': typeof AppCredenciadosRouteWithChildren
  '/app/editais': typeof AppEditaisRoute
  '/app/entrevistas': typeof AppEntrevistasRouteWithChildren
  '/app/funcoes': typeof AppFuncoesRoute
  '/app/situacoes': typeof AppSituacoesRoute
  '/app/sorteio': typeof AppSorteioRoute
  '/app/tramites': typeof AppTramitesRoute
  '/app': typeof AppIndexRoute
  '/app/contratos/gerar': typeof AppContratosGerarRoute
  '/app/credenciados/cadastrar': typeof AppCredenciadosCadastrarRoute
  '/app/entrevistas/agendar': typeof AppEntrevistasAgendarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/inscreva-se': typeof InscrevaSeRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/cadastro': typeof AppCadastroRoute
  '/app/contratos': typeof AppContratosRouteWithChildren
  '/app/convocacoes': typeof AppConvocacoesRoute
  '/app/credenciados': typeof AppCredenciadosRouteWithChildren
  '/app/editais': typeof AppEditaisRoute
  '/app/entrevistas': typeof AppEntrevistasRouteWithChildren
  '/app/funcoes': typeof AppFuncoesRoute
  '/app/situacoes': typeof AppSituacoesRoute
  '/app/sorteio': typeof AppSorteioRoute
  '/app/tramites': typeof AppTramitesRoute
  '/app/': typeof AppIndexRoute
  '/app/contratos/gerar': typeof AppContratosGerarRoute
  '/app/credenciados/cadastrar': typeof AppCredenciadosCadastrarRoute
  '/app/entrevistas/agendar': typeof AppEntrevistasAgendarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/inscreva-se'
    | '/login'
    | '/sitemap.xml'
    | '/app/cadastro'
    | '/app/contratos'
    | '/app/convocacoes'
    | '/app/credenciados'
    | '/app/editais'
    | '/app/entrevistas'
    | '/app/funcoes'
    | '/app/situacoes'
    | '/app/sorteio'
    | '/app/tramites'
    | '/app/'
    | '/app/contratos/gerar'
    | '/app/credenciados/cadastrar'
    | '/app/entrevistas/agendar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inscreva-se'
    | '/login'
    | '/sitemap.xml'
    | '/app/cadastro'
    | '/app/contratos'
    | '/app/convocacoes'
    | '/app/credenciados'
    | '/app/editais'
    | '/app/entrevistas'
    | '/app/funcoes'
    | '/app/situacoes'
    | '/app/sorteio'
    | '/app/tramites'
    | '/app'
    | '/app/contratos/gerar'
    | '/app/credenciados/cadastrar'
    | '/app/entrevistas/agendar'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/inscreva-se'
    | '/login'
    | '/sitemap.xml'
    | '/app/cadastro'
    | '/app/contratos'
    | '/app/convocacoes'
    | '/app/credenciados'
    | '/app/editais'
    | '/app/entrevistas'
    | '/app/funcoes'
    | '/app/situacoes'
    | '/app/sorteio'
    | '/app/tramites'
    | '/app/'
    | '/app/contratos/gerar'
    | '/app/credenciados/cadastrar'
    | '/app/entrevistas/agendar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  InscrevaSeRoute: typeof InscrevaSeRoute
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscreva-se': {
      id: '/inscreva-se'
      path: '/inscreva-se'
      fullPath: '/inscreva-se'
      preLoaderRoute: typeof InscrevaSeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tramites': {
      id: '/app/tramites'
      path: '/tramites'
      fullPath: '/app/tramites'
      preLoaderRoute: typeof AppTramitesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sorteio': {
      id: '/app/sorteio'
      path: '/sorteio'
      fullPath: '/app/sorteio'
      preLoaderRoute: typeof AppSorteioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/situacoes': {
      id: '/app/situacoes'
      path: '/situacoes'
      fullPath: '/app/situacoes'
      preLoaderRoute: typeof AppSituacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/funcoes': {
      id: '/app/funcoes'
      path: '/funcoes'
      fullPath: '/app/funcoes'
      preLoaderRoute: typeof AppFuncoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/entrevistas': {
      id: '/app/entrevistas'
      path: '/entrevistas'
      fullPath: '/app/entrevistas'
      preLoaderRoute: typeof AppEntrevistasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/editais': {
      id: '/app/editais'
      path: '/editais'
      fullPath: '/app/editais'
      preLoaderRoute: typeof AppEditaisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/credenciados': {
      id: '/app/credenciados'
      path: '/credenciados'
      fullPath: '/app/credenciados'
      preLoaderRoute: typeof AppCredenciadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/convocacoes': {
      id: '/app/convocacoes'
      path: '/convocacoes'
      fullPath: '/app/convocacoes'
      preLoaderRoute: typeof AppConvocacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contratos': {
      id: '/app/contratos'
      path: '/contratos'
      fullPath: '/app/contratos'
      preLoaderRoute: typeof AppContratosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cadastro': {
      id: '/app/cadastro'
      path: '/cadastro'
      fullPath: '/app/cadastro'
      preLoaderRoute: typeof AppCadastroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/entrevistas/agendar': {
      id: '/app/entrevistas/agendar'
      path: '/agendar'
      fullPath: '/app/entrevistas/agendar'
      preLoaderRoute: typeof AppEntrevistasAgendarRouteImport
      parentRoute: typeof AppEntrevistasRoute
    }
    '/app/credenciados/cadastrar': {
      id: '/app/credenciados/cadastrar'
      path: '/cadastrar'
      fullPath: '/app/credenciados/cadastrar'
      preLoaderRoute: typeof AppCredenciadosCadastrarRouteImport
      parentRoute: typeof AppCredenciadosRoute
    }
    '/app/contratos/gerar': {
      id: '/app/contratos/gerar'
      path: '/gerar'
      fullPath: '/app/contratos/gerar'
      preLoaderRoute: typeof AppContratosGerarRouteImport
      parentRoute: typeof AppContratosRoute
    }
  }
}

interface AppContratosRouteChildren {
  AppContratosGerarRoute: typeof AppContratosGerarRoute
}

const AppContratosRouteChildren: AppContratosRouteChildren = {
  AppContratosGerarRoute: AppContratosGerarRoute,
}

const AppContratosRouteWithChildren = AppContratosRoute._addFileChildren(
  AppContratosRouteChildren,
)

interface AppCredenciadosRouteChildren {
  AppCredenciadosCadastrarRoute: typeof AppCredenciadosCadastrarRoute
}

const AppCredenciadosRouteChildren: AppCredenciadosRouteChildren = {
  AppCredenciadosCadastrarRoute: AppCredenciadosCadastrarRoute,
}

const AppCredenciadosRouteWithChildren = AppCredenciadosRoute._addFileChildren(
  AppCredenciadosRouteChildren,
)

interface AppEntrevistasRouteChildren {
  AppEntrevistasAgendarRoute: typeof AppEntrevistasAgendarRoute
}

const AppEntrevistasRouteChildren: AppEntrevistasRouteChildren = {
  AppEntrevistasAgendarRoute: AppEntrevistasAgendarRoute,
}

const AppEntrevistasRouteWithChildren = AppEntrevistasRoute._addFileChildren(
  AppEntrevistasRouteChildren,
)

interface AppRouteChildren {
  AppCadastroRoute: typeof AppCadastroRoute
  AppContratosRoute: typeof AppContratosRouteWithChildren
  AppConvocacoesRoute: typeof AppConvocacoesRoute
  AppCredenciadosRoute: typeof AppCredenciadosRouteWithChildren
  AppEditaisRoute: typeof AppEditaisRoute
  AppEntrevistasRoute: typeof AppEntrevistasRouteWithChildren
  AppFuncoesRoute: typeof AppFuncoesRoute
  AppSituacoesRoute: typeof AppSituacoesRoute
  AppSorteioRoute: typeof AppSorteioRoute
  AppTramitesRoute: typeof AppTramitesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCadastroRoute: AppCadastroRoute,
  AppContratosRoute: AppContratosRouteWithChildren,
  AppConvocacoesRoute: AppConvocacoesRoute,
  AppCredenciadosRoute: AppCredenciadosRouteWithChildren,
  AppEditaisRoute: AppEditaisRoute,
  AppEntrevistasRoute: AppEntrevistasRouteWithChildren,
  AppFuncoesRoute: AppFuncoesRoute,
  AppSituacoesRoute: AppSituacoesRoute,
  AppSorteioRoute: AppSorteioRoute,
  AppTramitesRoute: AppTramitesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  InscrevaSeRoute: InscrevaSeRoute,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
